/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedReimbursementsIndexRouteImport } from './routes/_authenticated/reimbursements/index'
import { Route as AuthenticatedReimbursementsNewRouteImport } from './routes/_authenticated/reimbursements/new'
import { Route as AuthenticatedReimbursementsIdRouteImport } from './routes/_authenticated/reimbursements/$id'
import { Route as AuthenticatedReimbursementsIdEditRouteImport } from './routes/_authenticated/reimbursements/$id.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReimbursementsIndexRoute =
  AuthenticatedReimbursementsIndexRouteImport.update({
    id: '/reimbursements/',
    path: '/reimbursements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReimbursementsNewRoute =
  AuthenticatedReimbursementsNewRouteImport.update({
    id: '/reimbursements/new',
    path: '/reimbursements/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReimbursementsIdRoute =
  AuthenticatedReimbursementsIdRouteImport.update({
    id: '/reimbursements/$id',
    path: '/reimbursements/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReimbursementsIdEditRoute =
  AuthenticatedReimbursementsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedReimbursementsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reimbursements/$id': typeof AuthenticatedReimbursementsIdRouteWithChildren
  '/reimbursements/new': typeof AuthenticatedReimbursementsNewRoute
  '/reimbursements/': typeof AuthenticatedReimbursementsIndexRoute
  '/reimbursements/$id/edit': typeof AuthenticatedReimbursementsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reimbursements/$id': typeof AuthenticatedReimbursementsIdRouteWithChildren
  '/reimbursements/new': typeof AuthenticatedReimbursementsNewRoute
  '/reimbursements': typeof AuthenticatedReimbursementsIndexRoute
  '/reimbursements/$id/edit': typeof AuthenticatedReimbursementsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reimbursements/$id': typeof AuthenticatedReimbursementsIdRouteWithChildren
  '/_authenticated/reimbursements/new': typeof AuthenticatedReimbursementsNewRoute
  '/_authenticated/reimbursements/': typeof AuthenticatedReimbursementsIndexRoute
  '/_authenticated/reimbursements/$id/edit': typeof AuthenticatedReimbursementsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/reimbursements/$id'
    | '/reimbursements/new'
    | '/reimbursements/'
    | '/reimbursements/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/reimbursements/$id'
    | '/reimbursements/new'
    | '/reimbursements'
    | '/reimbursements/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/reimbursements/$id'
    | '/_authenticated/reimbursements/new'
    | '/_authenticated/reimbursements/'
    | '/_authenticated/reimbursements/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reimbursements/': {
      id: '/_authenticated/reimbursements/'
      path: '/reimbursements'
      fullPath: '/reimbursements/'
      preLoaderRoute: typeof AuthenticatedReimbursementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reimbursements/new': {
      id: '/_authenticated/reimbursements/new'
      path: '/reimbursements/new'
      fullPath: '/reimbursements/new'
      preLoaderRoute: typeof AuthenticatedReimbursementsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reimbursements/$id': {
      id: '/_authenticated/reimbursements/$id'
      path: '/reimbursements/$id'
      fullPath: '/reimbursements/$id'
      preLoaderRoute: typeof AuthenticatedReimbursementsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reimbursements/$id/edit': {
      id: '/_authenticated/reimbursements/$id/edit'
      path: '/edit'
      fullPath: '/reimbursements/$id/edit'
      preLoaderRoute: typeof AuthenticatedReimbursementsIdEditRouteImport
      parentRoute: typeof AuthenticatedReimbursementsIdRoute
    }
  }
}

interface AuthenticatedReimbursementsIdRouteChildren {
  AuthenticatedReimbursementsIdEditRoute: typeof AuthenticatedReimbursementsIdEditRoute
}

const AuthenticatedReimbursementsIdRouteChildren: AuthenticatedReimbursementsIdRouteChildren =
  {
    AuthenticatedReimbursementsIdEditRoute:
      AuthenticatedReimbursementsIdEditRoute,
  }

const AuthenticatedReimbursementsIdRouteWithChildren =
  AuthenticatedReimbursementsIdRoute._addFileChildren(
    AuthenticatedReimbursementsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReimbursementsIdRoute: typeof AuthenticatedReimbursementsIdRouteWithChildren
  AuthenticatedReimbursementsNewRoute: typeof AuthenticatedReimbursementsNewRoute
  AuthenticatedReimbursementsIndexRoute: typeof AuthenticatedReimbursementsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReimbursementsIdRoute:
    AuthenticatedReimbursementsIdRouteWithChildren,
  AuthenticatedReimbursementsNewRoute: AuthenticatedReimbursementsNewRoute,
  AuthenticatedReimbursementsIndexRoute: AuthenticatedReimbursementsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
